### ISSUE TITLE
@nestjs/swagger 4 compatibility

### ISSUE THREAD

**Issue by scieslickicc** [nestjsx/crud#340] opened 2019-12-09 14:38 UTC
Can you prepare version compatible with @nestjs/swagger 4 it have some breaking/API changes in version 4.0 :(

https://trilon.io/blog/nestjs-swagger-4-whats-new

https://docs.nestjs.com/recipes/swagger#migration-to-40

**Comment by DaVarga** [comment] 2019-12-10 12:59
Duplicate of #314

**Closed** 2019-12-10 13:08 UTC

**Comment by sebs** [comment] 2019-12-12 15:25
4.2.0 is from july, any way to release the latest patches?

**Comment by zMotivat0r** [comment] 2019-12-12 15:52
@sebs thanks for reminding the date of the latest release. Yes, the latest patches will be released after updating tests and wiki

**Comment by zMotivat0r** [comment] 2019-12-13 04:59
published `4.3.0-beta.0`
