### ISSUE TITLE
[Feature Request] paginate with pagination info

### ISSUE THREAD

**Issue by Diluka** [nestjsx/crud#18] opened 2019-01-10 02:52 UTC
currently it returns list only. for paging, there needs more info like `total`.
see https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/domain/PageImpl.java or https://github.com/pagehelper/Mybatis-PageHelper/blob/master/src/main/java/com/github/pagehelper/PageInfo.java

**Comment by zMotivat0r** [comment] 2019-01-10 13:52
Possible duplicate of #12. Closing this issue.

**Closed by zMotivat0r** 2019-01-10 13:52 UTC
Labels: duplicate :sleepy:

**Comment by zMotivat0r** [comment] 2019-03-22 20:48
Shipped with v3.0.0
