### ISSUE TITLE
Filters transformation

### ISSUE THREAD

**Issue by mkolbusz** [nestjsx/crud#528] opened 2020-06-01 12:15 UTC
Is it possible to transform filters received from the client?
I have a model with enum field and API client sends the field with a string value. I need to map this string value to the integer index of the enum to be able to filter by the enum value.
For example, the client sends:
`?filter=status||$eq||"active"`
With the enum `enum STATUS { ACTIVE, INACTIVE}` I want to transform `"active"` string from request query to 0
How to achieve it in an easy way using your library?

**Comment by zMotivat0r** [comment] 2020-06-01 12:37
Why doesn't that api client use the same enum?
Is this api client used programmatically? Or is it used by a human and it needs to be easily readable by a human?
If it's used programmatically then I don't see any reason why you would spend time/resources to transform this and almost for sure increase a latency? (even not too much of course).
And answering your question - you can use your own interceptors/pipes or even controllers/service helper functions - it's totally up you.
I'm closing this since it's not a bug report or any other issue

**Closed by zMotivat0r** 2020-06-01 12:37 UTC
