### ISSUE TITLE
How to hide some fields like password?

### ISSUE THREAD

**Issue by erikhenriq** [nestjsx/crud#183] opened 2019-07-19 22:11 UTC
How to return a custom model? For example, hide password or whatever i want and return response?

```
@Crud({
  model: {
    type: User,
  },
  routes: {
    getManyBase: {
      decorators: [
        UseGuards(AuthGuard()),
      ],
    },
  },
})
@Controller('users')
```
When i call the endpoint like `GET /users` it returns me something like this:

```
[
    {
        "id": 1,
        "email": "erik.hac@outlook.com",
        "password": "43587y34t9078eryht457089649",
        "isActive": true,
        "isEmailConfirmed": true,
        "createdAt": "2019-07-16T03:05:50.020Z",
        "updatedAt": "2019-07-19T21:11:16.032Z",
        "lastSession": "2019-07-19T21:11:16.007Z",
        "resetPasswordExpire": null,
        "resetPasswordToken": null
    }
]
```

**Comment by zMotivat0r** [comment] 2019-07-20 08:31
You can use [exclude](https://github.com/nestjsx/crud/wiki/Controllers#exclude) in the `CrudOptions`

**Comment by eranshmil** [comment] 2019-10-10 14:02
@zMotivat0r Hi, thanks for your hard work.
The exclude option isn't supposed to exclude also from the response of the create requests?

**Comment by zMotivat0r** [comment] 2019-10-10 15:41
@eranshmil it's been fixed but not released yet. Will be included in the upcoming release soon

**Comment by zMotivat0r** [comment] 2019-10-12 06:26
@eranshmil I'm going to publish RC version today probably. Will let you know ;)

**Comment by eranshmil** [comment] 2019-10-16 08:31
@zMotivat0r I updated to the alpha version and still I get the excluded properties in the response.

**Comment by zMotivat0r** [comment] 2019-10-16 11:17
@eranshmil I'm pretty much sure that if you specify in the CrudOptions `query.exclude` with some array of entity's fields, then you won't get that field in the create/update/replace response.
So, if I add `exclude: ['domain']` here https://github.com/nestjsx/crud/blob/883cef9fe7e8786002a30cbed0438ed967754ef7/integration/crud-typeorm/companies/companies.controller.ts#L12-L17 it works as it should.
If you still have issues with that, I would ask you to create a repo with the minimum reproduction of your bug. Thanks!

**Comment by Quaiks** [comment] 2019-11-20 21:33
Hello!!

If I add a field to `query.exclude` for example, `password`, I do not get the field when a do a `GET` request but when a create a new entity the field is returned.

**Comment by erikhenriq** [comment] 2019-11-23 14:06
Any solution/workaround on this? @Quaiks can you show us `package.json` ?

**Comment by zMotivat0r** [comment] 2019-12-28 09:36
fixed with `4.3.0`:
- `exclude` works wor every route
- also [serialization](https://github.com/nestjsx/crud/wiki/Controllers#serialize) has been added

**Closed by zMotivat0r** 2019-12-28 09:36 UTC

**Comment by cleivson** [comment] 2020-01-14 05:58
> * `exclude` works wor every route

@zMotivat0r , I don't know if it's by design, but when we set ```returnDeleted: true```, the field in excluded field is still returned.

Example:

```
@Crud({
  model: {
    type: User,
  },
  routes: {
    deleteOneBase: {
      returnDeleted: true,
    }, // TODO add test to check whether or not the user is being returned
  },
  query: {
    exclude: [
      propertyOf<User>('passwordHash'), 
      // passwordHash is still returned when deleting an user
    ],
  },
  validation: {
    transform: true,
  },
})
```

**Comment by zMotivat0r** [comment] 2020-01-14 06:45
@cleivson yeah, it's by design will return a shallow entity. But you can use [respose dto](https://github.com/nestjsx/crud/wiki/Controllers#serialize) to exclude or transform any property

**Comment by cleivson** [comment] 2020-01-14 22:42
@zMotivat0r 
> @cleivson yeah, it's by design will return a shallow entity. But you can use [respose dto](https://github.com/nestjsx/crud/wiki/Controllers#serialize) to exclude or transform any property

You think the ```exclude``` behavior could be extended for delete endpoint? I don't think of any cases where the users could benefit of receiving more fields in a call to ```delete``` than he would receive in a call to ```get```

**Comment by zMotivat0r** [comment] 2020-01-15 04:40
@cleivson it works in both sides - in `get` request a user can get more fields too when there are joins for example. As I said, there is a serialization enabled, so one can use response dto to exclude/transform/add properties
