### ISSUE TITLE
crud-routes.factory some method can be protected so it can be extended

### ISSUE THREAD

**Issue by muratbeser** [nestjsx/crud#595] opened 2020-08-17 13:10 UTC
Hi, currently I'm trying to extend this library for sometype of microservice. 

every method is private this preventing extending route-factory is there technical reason ? if not can we make some of the methods protected ?

**Comment by zMotivat0r** [comment] 2020-08-17 17:15
duplicate of https://github.com/nestjsx/crud/issues/593

**Closed by zMotivat0r** 2020-08-17 17:15 UTC
Labels: type: duplicate
